export const theme = {
  colors: {
    profileBgColor: 'honeydew',
    secondBgColor: 'lavenderblush',
    avatarBgColor: 'steelblue',
    labelBgColor: 'steelblue',
    cardBgColor: 'lightskyblue',
    statsBgColor: 'rgb(247, 244, 241)',
    mainTextColor: 'black',
    white: '#ffffff',
    secondaryTextColor: 'grey',
    isOnline: 'lightgreen',
    isOffline: 'lightcoral',
    isOnlineText: 'tomato',
    isOfflineText: 'darkmagenta',
    tableBgColor: '#00bcd5',
    tableRowMainColor: '#85929e',
    tableRowSecondaryColor: '#f0f8fd',
  },
  spacing: (value) => `${value*4}px`,
};
